driverName=oracle.jdbc.driver.OracleDriver
url=jdbc:oracle:thin:@localhost:1521:orcl
userName=system
password=Oracle@2024
SELECT_ALL_QUERY=select * from products
SELECET_SINGLE_QUERY=select * from products where product_id=?
INSERT_QUERY=insert into products(product_id,product_name,product_desc,product_price,product_released_on,category_id) values(?,?,?,?,?,?)
UPDATE_QUERY=update products set product_name=?,product_desc=?,product_price=?,product_released_on=?,category_id=? where product_id=?
DELETE_QUERY=delete from products where product_id=?